
version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db

  web:
    build:
      context: ./
    image: weegius/final
    ports:
      - "5000:5000"
    environment:
      - DB_URL=mongodb://srv-captain--final-db/mydatabase?authSource=admin
      - SKEY=o1HM3lo7Snqp4gHM@^93e7g%fe&pgEZ#ep
      - PUB_KEY=12ced8960637e7633241
    depends_on:
      - mongodb